In [12]:
import matplotlib.pyplot as plt
import numpy as np
import SegDataGenerator as gen
%matplotlib inline

batch_size = 1
data_path = 'data/dataset_256x256.npz'
model_path = 'model/'
steps_per_epoch=5
epochs=5
validation_step=2

In [16]:
def plots(imgs, figsize=(12,6), rows=1, title=None, titles=None):
    f = plt.figure(figsize=figsize)
    if title is not None: plt.title(title)
    for i in range(len(imgs)):
        sp = f.add_subplot(rows, len(imgs)//rows, i+1)
        sp.axis('Off')
        if titles is not None: sp.set_title(titles[i], fontsize=8)
        plt.imshow(np.squeeze(imgs[i]), cmap='gray')

In [17]:
trainGenerator = gen.SegDataGenerator(validation_split=0.2, width_shift_range=0.02,
                                   height_shift_range=0.02, zoom_range=0.1,
                                   horizontal_flip=True, vertical_flip=True,
                                   samplewise_center=False, samplewise_std_normalization=False,
                                   elastic_transform=False, rotation_right=False)
train_data = trainGenerator.flow_from_directory(data_path, subset='training', batch_size=batch_size,
                                               class_mode='segmentation', color_mode='grayscale',
                                               use_contour=False, label_bw=True)

Reading from previously loaded data.


KeyError: 'C_train is not a file in the archive'

In [ ]:
# image, seg, contour = next(train_data)
# plots([image, seg, contour])
image, seg = next(train_data)
plots([image, seg])
print(seg.shape)

In [8]:
print(seg[0,50:60,50:60,0])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
